/* AUTO-GENERATED by CMake — do not edit. */
#include <stddef.h>
typedef void (*test_fn)(int, int);
extern void test_01_clear_black(int,int);
extern void test_02_clear_red(int,int);
extern void test_03_scissor_clear(int,int);
extern void test_04_partial_viewport_clear(int,int);
extern void test_05_multi_clear_stripes(int,int);
extern void test_06_get_viewport(int,int);
extern void test_07_matrix_identity(int,int);
extern void test_08_matrix_translate(int,int);
extern void test_09_matrix_stack(int,int);
extern void test_100_showcase(int,int);
extern void test_10_ortho_projection(int,int);
extern void test_11_triangle_ccw(int,int);
extern void test_12_triangle_cw_culled(int,int);
extern void test_13_triangle_depth(int,int);
extern void test_14_triangle_frustum(int,int);
extern void test_15_two_tris_depth(int,int);
extern void test_16_flat_shaded(int,int);
extern void test_17_gouraud_rgb(int,int);
extern void test_18_fullscreen_quad(int,int);
extern void test_19_degenerate_triangle(int,int);
extern void test_20_triangle_at_edges(int,int);
extern void test_21_clip_left(int,int);
extern void test_22_clip_right(int,int);
extern void test_23_clip_top(int,int);
extern void test_24_clip_bottom(int,int);
extern void test_25_clip_near(int,int);
extern void test_26_clip_far(int,int);
extern void test_27_clip_all_planes(int,int);
extern void test_28_clip_offscreen_but_visible(int,int);
extern void test_29_clip_quad_seam(int,int);
extern void test_30_clip_many_triangles(int,int);
extern void test_31_translate(int,int);
extern void test_32_rotate_x(int,int);
extern void test_33_rotate_y(int,int);
extern void test_34_rotate_z(int,int);
extern void test_35_scale_nonuniform(int,int);
extern void test_36_rotate_translate(int,int);
extern void test_37_orbit(int,int);
extern void test_38_perspective_60fov(int,int);
extern void test_39_aspect_correction(int,int);
extern void test_40_hierarchical_transform(int,int);
extern void test_41_tex_checkerboard(int,int);
extern void test_42_tex_gradient_bilinear(int,int);
extern void test_43_tex_repeat(int,int);
extern void test_44_tex_clamp(int,int);
extern void test_45_tex_many_repeats(int,int);
extern void test_46_tex_alpha_cutout(int,int);
extern void test_47_tex_modulate(int,int);
extern void test_48_tex_replace(int,int);
extern void test_49_tex_decal(int,int);
extern void test_50_multitexture(int,int);
extern void test_51_directional_light(int,int);
extern void test_52_ambient_only(int,int);
extern void test_53_diffuse_lambert(int,int);
extern void test_54_specular_blinn(int,int);
extern void test_55_point_light_attenuation(int,int);
extern void test_56_multi_lights(int,int);
extern void test_57_icosphere_lit(int,int);
extern void test_58_colored_material(int,int);
extern void test_59_emission(int,int);
extern void test_60_normalize(int,int);
extern void test_61_tessellated_grid(int,int);
extern void test_62_icosphere_subdiv(int,int);
extern void test_63_uv_sphere(int,int);
extern void test_64_cylinder(int,int);
extern void test_65_torus(int,int);
extern void test_66_bezier_patch(int,int);
extern void test_67_extrusion(int,int);
extern void test_68_loft(int,int);
extern void test_69_superquadric(int,int);
extern void test_70_heightfield(int,int);
extern void test_71_fog_exp2(int,int);
extern void test_72_fog_linear(int,int);
extern void test_73_fog_exp(int,int);
extern void test_74_fog_colored(int,int);
extern void test_75_alpha_blend(int,int);
extern void test_76_additive_blend(int,int);
extern void test_77_alpha_test_edge(int,int);
extern void test_78_transparent_stack(int,int);
extern void test_79_premult_alpha(int,int);
extern void test_80_blend_depth(int,int);
extern void test_81_vbo_simple(int,int);
extern void test_82_vbo_interleaved_pc(int,int);
extern void test_83_vbo_interleaved_pnct(int,int);
extern void test_84_indexed_draw(int,int);
extern void test_85_multi_vbos(int,int);
extern void test_86_buffer_subdata(int,int);
extern void test_87_large_mesh(int,int);
extern void test_88_instanced_manual(int,int);
extern void test_89_dynamic_vbo(int,int);
extern void test_90_multi_drawarrays(int,int);
extern void test_91_dot3_baseline(int,int);
extern void test_92_normalmap_pattern(int,int);
extern void test_93_normalmap_depth(int,int);
extern void test_94_lit_textured_sphere(int,int);
extern void test_95_scene_sphere_ground(int,int);
extern void test_96_building_cube(int,int);
extern void test_97_multiple_buildings(int,int);
extern void test_98_city_block(int,int);
extern void test_99_moving_camera(int,int);

typedef struct { const char *name; test_fn fn; } entry;
static const entry tests[] = {
    { "test_01_clear_black", test_01_clear_black },
    { "test_02_clear_red", test_02_clear_red },
    { "test_03_scissor_clear", test_03_scissor_clear },
    { "test_04_partial_viewport_clear", test_04_partial_viewport_clear },
    { "test_05_multi_clear_stripes", test_05_multi_clear_stripes },
    { "test_06_get_viewport", test_06_get_viewport },
    { "test_07_matrix_identity", test_07_matrix_identity },
    { "test_08_matrix_translate", test_08_matrix_translate },
    { "test_09_matrix_stack", test_09_matrix_stack },
    { "test_100_showcase", test_100_showcase },
    { "test_10_ortho_projection", test_10_ortho_projection },
    { "test_11_triangle_ccw", test_11_triangle_ccw },
    { "test_12_triangle_cw_culled", test_12_triangle_cw_culled },
    { "test_13_triangle_depth", test_13_triangle_depth },
    { "test_14_triangle_frustum", test_14_triangle_frustum },
    { "test_15_two_tris_depth", test_15_two_tris_depth },
    { "test_16_flat_shaded", test_16_flat_shaded },
    { "test_17_gouraud_rgb", test_17_gouraud_rgb },
    { "test_18_fullscreen_quad", test_18_fullscreen_quad },
    { "test_19_degenerate_triangle", test_19_degenerate_triangle },
    { "test_20_triangle_at_edges", test_20_triangle_at_edges },
    { "test_21_clip_left", test_21_clip_left },
    { "test_22_clip_right", test_22_clip_right },
    { "test_23_clip_top", test_23_clip_top },
    { "test_24_clip_bottom", test_24_clip_bottom },
    { "test_25_clip_near", test_25_clip_near },
    { "test_26_clip_far", test_26_clip_far },
    { "test_27_clip_all_planes", test_27_clip_all_planes },
    { "test_28_clip_offscreen_but_visible", test_28_clip_offscreen_but_visible },
    { "test_29_clip_quad_seam", test_29_clip_quad_seam },
    { "test_30_clip_many_triangles", test_30_clip_many_triangles },
    { "test_31_translate", test_31_translate },
    { "test_32_rotate_x", test_32_rotate_x },
    { "test_33_rotate_y", test_33_rotate_y },
    { "test_34_rotate_z", test_34_rotate_z },
    { "test_35_scale_nonuniform", test_35_scale_nonuniform },
    { "test_36_rotate_translate", test_36_rotate_translate },
    { "test_37_orbit", test_37_orbit },
    { "test_38_perspective_60fov", test_38_perspective_60fov },
    { "test_39_aspect_correction", test_39_aspect_correction },
    { "test_40_hierarchical_transform", test_40_hierarchical_transform },
    { "test_41_tex_checkerboard", test_41_tex_checkerboard },
    { "test_42_tex_gradient_bilinear", test_42_tex_gradient_bilinear },
    { "test_43_tex_repeat", test_43_tex_repeat },
    { "test_44_tex_clamp", test_44_tex_clamp },
    { "test_45_tex_many_repeats", test_45_tex_many_repeats },
    { "test_46_tex_alpha_cutout", test_46_tex_alpha_cutout },
    { "test_47_tex_modulate", test_47_tex_modulate },
    { "test_48_tex_replace", test_48_tex_replace },
    { "test_49_tex_decal", test_49_tex_decal },
    { "test_50_multitexture", test_50_multitexture },
    { "test_51_directional_light", test_51_directional_light },
    { "test_52_ambient_only", test_52_ambient_only },
    { "test_53_diffuse_lambert", test_53_diffuse_lambert },
    { "test_54_specular_blinn", test_54_specular_blinn },
    { "test_55_point_light_attenuation", test_55_point_light_attenuation },
    { "test_56_multi_lights", test_56_multi_lights },
    { "test_57_icosphere_lit", test_57_icosphere_lit },
    { "test_58_colored_material", test_58_colored_material },
    { "test_59_emission", test_59_emission },
    { "test_60_normalize", test_60_normalize },
    { "test_61_tessellated_grid", test_61_tessellated_grid },
    { "test_62_icosphere_subdiv", test_62_icosphere_subdiv },
    { "test_63_uv_sphere", test_63_uv_sphere },
    { "test_64_cylinder", test_64_cylinder },
    { "test_65_torus", test_65_torus },
    { "test_66_bezier_patch", test_66_bezier_patch },
    { "test_67_extrusion", test_67_extrusion },
    { "test_68_loft", test_68_loft },
    { "test_69_superquadric", test_69_superquadric },
    { "test_70_heightfield", test_70_heightfield },
    { "test_71_fog_exp2", test_71_fog_exp2 },
    { "test_72_fog_linear", test_72_fog_linear },
    { "test_73_fog_exp", test_73_fog_exp },
    { "test_74_fog_colored", test_74_fog_colored },
    { "test_75_alpha_blend", test_75_alpha_blend },
    { "test_76_additive_blend", test_76_additive_blend },
    { "test_77_alpha_test_edge", test_77_alpha_test_edge },
    { "test_78_transparent_stack", test_78_transparent_stack },
    { "test_79_premult_alpha", test_79_premult_alpha },
    { "test_80_blend_depth", test_80_blend_depth },
    { "test_81_vbo_simple", test_81_vbo_simple },
    { "test_82_vbo_interleaved_pc", test_82_vbo_interleaved_pc },
    { "test_83_vbo_interleaved_pnct", test_83_vbo_interleaved_pnct },
    { "test_84_indexed_draw", test_84_indexed_draw },
    { "test_85_multi_vbos", test_85_multi_vbos },
    { "test_86_buffer_subdata", test_86_buffer_subdata },
    { "test_87_large_mesh", test_87_large_mesh },
    { "test_88_instanced_manual", test_88_instanced_manual },
    { "test_89_dynamic_vbo", test_89_dynamic_vbo },
    { "test_90_multi_drawarrays", test_90_multi_drawarrays },
    { "test_91_dot3_baseline", test_91_dot3_baseline },
    { "test_92_normalmap_pattern", test_92_normalmap_pattern },
    { "test_93_normalmap_depth", test_93_normalmap_depth },
    { "test_94_lit_textured_sphere", test_94_lit_textured_sphere },
    { "test_95_scene_sphere_ground", test_95_scene_sphere_ground },
    { "test_96_building_cube", test_96_building_cube },
    { "test_97_multiple_buildings", test_97_multiple_buildings },
    { "test_98_city_block", test_98_city_block },
    { "test_99_moving_camera", test_99_moving_camera },

};
int  sg_test_count(void) { return (int)(sizeof(tests)/sizeof(tests[0])); }
const char *sg_test_name(int i) { return (i < 0 || i >= sg_test_count()) ? "" : tests[i].name; }
void sg_test_run(int i, int w, int h) { if (i >= 0 && i < sg_test_count()) tests[i].fn(w, h); }
